---
title: 'Decoding Analysis'
output: pdf_document
---


```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = TRUE)


```



```{r}

load('/home/em939/shared_projects/allen_brain_observatory_data/allen_binned_data/100bins_5sampled/session_715093703_100bins_5sampled.Rda')

nrow(binned_data)




```






# Run the decoding analysis 


```{r eval=FALSE}

devtools::install_github("emeyers/NeuroDecodeR")

library(NeuroDecodeR)

# I have access to William's files so I can load this data...
#binned_data <- file.path('/home/wz354/project/NeuralDecoding/NeuralDecoding/data/binned/ZD_150bins_50#sampled.Rda') 

binned_data <- file.path('/home/em939/research/test_william_cluster_code/gitignore/ZD_150bins_50sampled.Rda') 



ds <- ds_basic(
	binned_data = binned_data,
	labels = 'combined_ID_position',
	num_label_repeats_per_cv_split = 1,
	num_cv_splits = 2,
	num_resample_sites = 132) 


cl <- cl_max_correlation(return_decision_values = TRUE) 


fp_zs <- fp_zscore()

fps <- list(fp_zs) 


rm_main <- rm_main_results(
	 include_norm_rank_results = TRUE)
rm_cm <- rm_confusion_matrix(
	 save_TCD_results = TRUE,
	 create_decision_vals_confusion_matrix = TRUE)
rms <- list(rm_main, rm_cm)


cv <- cv_standard(
	 datasource = ds,
	 classifier = cl, 
	 feature_preprocessors = fps,
	 result_metrics = rms) 


DECODING_RESULTS <- run_decoding(cv)

paste('The analysis ID is:',
        DECODING_RESULTS$cross_validation_paramaters$analysis_ID)


log_save_results(DECODING_RESULTS, 
	file.path('/home/em939/research/test_william_cluster_code/results', 'decoding_results', 'decoding_result_files', ''))


```





# Plot some results 


```{r eval = FALSE}

plot(DECODING_RESULTS$rm_main_results, type = 'line') 

plot(DECODING_RESULTS$rm_main_results) 

plot(DECODING_RESULTS$rm_confusion_matrix) 

```



